
package ec.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-08-03T17:19:59.667-05:00
 * Generated source version: 2.7.11
 */

@WebFault(name = "Exception", targetNamespace = "http://service.AppDis.ups.edu.ec/")
public class Exception_Exception extends java.lang.Exception {
    
    private ec.soap.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, ec.soap.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, ec.soap.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public ec.soap.Exception getFaultInfo() {
        return this.exception;
    }
}
