package ec.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-08-03T17:19:59.674-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://service.AppDis.ups.edu.ec/", name = "Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Soap {

    @WebMethod(operationName = "Pedido")
    @RequestWrapper(localName = "Pedido", targetNamespace = "http://service.AppDis.ups.edu.ec/", className = "ec.soap.Pedido")
    @ResponseWrapper(localName = "PedidoResponse", targetNamespace = "http://service.AppDis.ups.edu.ec/", className = "ec.soap.PedidoResponse")
    public void pedido(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws Exception_Exception;
}
