
package ec.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-08-03T17:19:59.629-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class Soap_SoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.AppDis.ups.edu.ec/", "SoapService");

    private Soap_SoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SoapService ss = new SoapService(wsdlURL, SERVICE_NAME);
        Soap port = ss.getSoapPort();  
        
        {
        System.out.println("Invoking pedido...");
        int _pedido_arg0 = 1;
        int _pedido_arg1 = 3;
        try {
            port.pedido(_pedido_arg0, _pedido_arg1);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
