package ec.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-08-03T17:19:59.680-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "SoapService", 
                  wsdlLocation = "http://localhost:8080/Guapan/Soap?wsdl",
                  targetNamespace = "http://service.AppDis.ups.edu.ec/") 
public class SoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.AppDis.ups.edu.ec/", "SoapService");
    public final static QName SoapPort = new QName("http://service.AppDis.ups.edu.ec/", "SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Guapan/Soap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Guapan/Soap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "SoapPort")
    public Soap getSoapPort() {
        return super.getPort(SoapPort, Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "SoapPort")
    public Soap getSoapPort(WebServiceFeature... features) {
        return super.getPort(SoapPort, Soap.class, features);
    }

}
